server:
  port: 7905
spring:
  application:
    name: microservice-simple-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
