server:
  port: 7906
spring:
  application:
    name: microservice-simple-consumer-movie-feign-customizing
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
